# Generated by Django 5.0.1 on 2024-01-17 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nepa_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provience',
            name='image',
            field=models.ImageField(upload_to='Provience_Image/'),
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='all_image/')),
                ('provience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Nepa_application.provience')),
            ],
        ),
    ]
