# Generated by Django 5.0.1 on 2024-01-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nepa_application', '0002_alter_provience_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing_Provience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('major_description', models.TextField()),
                ('minor_description', models.TextField()),
                ('proviencenumber', models.CharField(max_length=10)),
            ],
        ),
    ]
