# Generated by Django 5.0.1 on 2024-01-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nepa_application', '0004_contact_us_delete_landing_provience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
