# Generated by Django 5.0.1 on 2024-02-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nepa_application', '0006_post_alter_contact_us_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
