# Generated by Django 5.0.2 on 2024-02-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nepa_application', '0008_t_image_topic_delete_post_t_image_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='provience',
            new_name='province',
        ),
    ]
