# Generated by Django 5.0.2 on 2024-02-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nepa_application', '0009_rename_provience_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Nepa_application.province'),
        ),
    ]
