# Generated by Django 5.0.2 on 2024-02-18 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nepa_application', '0016_remove_topic_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
