# Generated by Django 5.0.2 on 2024-02-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nepa_application', '0017_topic_is_verified_topic_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
