# Generated by Django 5.0.2 on 2024-02-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nepa_application', '0019_user_alter_topic_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
