# Generated by Django 5.0.2 on 2024-02-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nepa_application', '0020_alter_topic_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
