# Generated by Django 5.0.2 on 2024-02-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nepa_application', '0022_remove_topic_category_topic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Nepa_application.category'),
        ),
    ]
