# Generated by Django 4.2.1 on 2024-02-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nepa_application', '0026_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='commentCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
