# Generated by Django 4.2.1 on 2024-03-03 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nepa_application', '0028_topic_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'ordering': ['-post_date']},
        ),
        migrations.AddField(
            model_name='contact_us',
            name='post_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
